

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    image: event-planner-api:latest
    container_name: event-planner-api
    restart: unless-stopped
    env_file:
    - ./app/.env
    volumes:
      - ./app:/ProjectText2Title/app
      - ./rabbitmq:/ProjectText2Title/rabbitmq
    networks:
      - event-planner-network


  ml_worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.mlworker
    image: event-planner-ml-worker:latest
    container_name: event-planner-ml-worker
    restart: unless-stopped
    volumes:
      - ./ml_worker:/ProjectText2Title/ml_worker
      - ./rabbitmq:/ProjectText2Title/rabbitmq
    networks:
      - event-planner-network

  web-proxy:
    image: nginx:1.29-alpine
    container_name: event-planner-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - event-planner-network

  rabbitmq:
    image: rabbitmq:3.13.1-management-alpine
    container_name: rabbitmq_for_planner
    hostname: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "15672:15672"  # Management UI
      - "5672:5672"    # AMQP protocol
    networks:
      - event-planner-network

  database:
    image: postgres:latest
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - event-planner-network

  ollama:
    image: ollama/ollama
    container_name: gemma-server
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_MODELS=mistral:7b-instruct
    networks:
      - event-planner-network

volumes:
  rabbitmq_data:
    driver: local
  postgres_data:
    driver: local
  ollama_data:

networks:
  event-planner-network:
    name: event-planner-network
    driver: bridge